### PR TITLE
fix missing theme background application

### LINKED ISSUE #81: Theme: background isn't applied everywhere
Just tried the background theming option for the first time

<details>
<summary> <code> ~/.config/tickrs/config.yml </code> </summary>

```yml
theme:
  background: '#403E41'
```

</details>

| | line | candle |
| - | - | - |
| summary of 1 | Screenshot_20210220_191115 | Screenshot_20210220_190458 |
| summary of 3 | Screenshot_20210220_191301 | Screenshot_20210220_190139
| stock view | Screenshot_20210220_191435 | Screenshot_20210220_190300 |

### PR DESCRIPTION
**Pull request by tarkah**
Resolves #81

### CODE REVIEW

**Comment by miraclx** [comment]
👍🏽

File: src/theme.rs [hunk 1]
```diff
@@ -1,7 +1,12 @@
 use serde::Deserialize;
-use tui::style::Color;
+use tui::style::{Color, Style};
 
 use self::de::deserialize_option_color_hex_string;
+use crate::THEME;
+
+pub fn style() -> Style {
```
Comment (miraclx) [inline src/theme.rs:7]: Sure we shouldn't ```#[inline]``` these calls? It's called many times under short spans of time it might be costly not to.

Comment (tarkah) [reply src/theme.rs:7]: Yeah wouldn't hurt. I can also try changing `lto = true` for release build and I don't even think this will matter? Let me see what the performance impacts are.

Comment (tarkah) [reply src/theme.rs:7]: Differences are indistinguishable from CPU usage (at least monitoring for a few seconds with top / htop). As in, there may be some difference but without more sophisticated profiling I'm not going to figure it out. However Binary size is much smaller. So maybe I'll enable LTO. 

| Metric | No changes | Inline style() | No inline, LTO = true | Inline & LTO= true |
| - | - | - | - | - |
| CPU Usage | ~2.6% | ~2.6% | ~2.6% | ~2.6% |
| Binary Size | 11MB | 11MB | 7.8MB | 7.8MB |

To err on the side of caution, I'll inline this as well
